name: python-app
on:
   push:
     branches:
        - '**'
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: install python 3.9
          uses: actions/setup-python@v4
          with:
             python-version: '3.9'
        - name: pyhton version
          run: python --version
        - name: Install Dependencies
          run: |
             python -m pip install --upgrade pip
             pip install pytest flake8
            
        - name: Run version
          run: flake8 .--version
           
        - name: flake lint
          run: flake8
          
        - name: Run Tests
          run: pytest --version
